version: "3.8"
services:
 web:
  build: ./nginx/
  container_name: web1
  ports:
   - "8080:80"
  links:
   - "php"
  volumes:
   - "./www/html/:/var/www/html/"
  
 php:
   build: ./php/
   container_name: php1
   expose:
    - "9000"
   volumes:
    - "./www/html/:/var/www/html/"
 
 db:
  build: ./db/
  container_name: db
  volumes:
   - "/var/lib/mariadb"
  environment:
   MYSQL_ROOT_PASSWORD: "12345"

